name: Validate GHSA IDs in .jsonnet Files

on:
  pull_request:
    branches:
      - main

jobs:
  validate-ghsa:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the PR Branch
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0  # Fetch full history for accurate diff

      # Step 2: Set Up Python Environment
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you need

      # Step 3: Install Python Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          # Install any required Python packages here
          # For example: pip install -r scripts/jsonnet_validation_requirements.txt
          if [ -f scripts/jsonnet_validation_requirements.txt ]; then pip install -r scripts/jsonnet_validation_requirements.txt; fi

      # Step 4: Determine Changed .jsonnet Files in /rules/ssc/
      - name: Determine Changed .jsonnet Files in /rules/ssc/
        id: changed_files
        run: |
          echo "Fetching changes from the base branch..."
          git fetch origin ${{ github.base_ref }}

          echo "Listing changed files in the PR..."
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)

          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Filter files within /rules/ssc/, ending with .jsonnet, and matching GHSA pattern
          SSC_JSONNET_FILES=$(echo "$CHANGED_FILES" | grep '^rules/ssc/' | grep -E '^rules/ssc/.*GHSA-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}[^/]*\.jsonnet$' || true)

          echo "Changed .jsonnet files in /rules/ssc/:"
          echo "$SSC_JSONNET_FILES"

          # Convert the list to space-separated arguments, removing any leading/trailing whitespace
          FILES_LIST=$(echo "$SSC_JSONNET_FILES" | tr '\n' ' ' | xargs)

          echo "files=$FILES_LIST" >> $GITHUB_OUTPUT

          # Debug: Output the files list
          echo "Files list: $FILES_LIST"

      # Step 5: Run Validation Only If Relevant Files Are Changed
      - name: Validate GHSA IDs
        if: ${{ steps.changed_files.outputs.files != '' }}
        run: |
          echo "Running GHSA ID validation on changed files..."

          # Define the path to the Python script
          VALIDATION_SCRIPT="./scripts/validate_jsonnet.py"

          # Check if the validation script exists
          if [ ! -f "$VALIDATION_SCRIPT" ]; then
            echo "Validation script not found at $VALIDATION_SCRIPT"
            exit 1
          fi

          # Execute the Python validation script, passing the list of files as arguments
          python "$VALIDATION_SCRIPT" ${{ steps.changed_files.outputs.files }}

      # Step 6: Notify CI Skipped
      - name: Notify CI Skipped
        if: ${{ steps.changed_files.outputs.files == '' }}
        run: |
          echo "No relevant .jsonnet file changes in /rules/ssc/. Skipping GHSA ID validation."
